### ISSUE TITLE
Cache with funcs

### ISSUE THREAD

**Issue by Lakritzator** [azzlack/provision#21]
I am currently searching for a cache which covers my needs, and found this project.
It looks nice, but doesn't match my needs, and I just wanted to know if it would be hard (possible) to build a provider which does fit my needs.

I would like to have a cache (e.g. a memory cache) which can be configured with a lamba ( or actually a Func<TKey, Task<TCacheItem>> ).
When an item is requested, the provider should use the cache to check if the item is in it, if not the function is called to retrieve the item.
Now, this in general is not yet very complex, I think it gets tricky here:
- Every other call to get the item should be blocked while the result is being retrieved
- The function can (must?) be async, awaiting should be done..

Background is having a Rest-API based system where certain resources should be cached for a configurable time, and retrieved only if needed. I do not need a system where the expiring resources are automatically updated, although this would be okay if it's configurable.

I could have written this myself (meaning completely, without provision) but why when reuse is possible, and I certainly don't want to reinvent the wheel.

Maybe this is already possible, and I just overlooked this?

**Comment by azzlack** [comment]
That is certainly possible, will look into adding it to the next release. (Hopefully by the end of this week)

**Comment by Lakritzator** [comment]
In the mean time, I build the following:
https://github.com/dapplo/Dapplo.Utils/blob/master/Dapplo.Utils/AsyncMemoryCache.cs
With an example here:
https://github.com/dapplo/Dapplo.Utils/blob/master/Dapplo.Utils.Tests/Cache/AsyncBitmapCache.cs

As this works for me, although there is probably some (a lot?) of potential for improvements but, I don't think I will need a different solution. You are of course more than welcome to take a look at it, and improve it for your project. In general I don't like to maintain code which other people might understand better, caching is not my primary focus. But to add a dependency on multiple project only for this functionality is another thing :smile:
