### ISSUE TITLE
Don't be dependent on C5 assembly, implement the necessary parts in Provision

### ISSUE THREAD

**Issue by azzlack** [azzlack/provision#8]

**Comment by Lakritzator** [comment]
Disclaimer: This is not a complaint, just something I noticed:exclamation: 

In https://www.nuget.org/packages/Provision/3.0.3 C5 is still a dependency.

**Comment by azzlack** [comment]
@Lakritzator No offense taken :-)  
This issue was created at a time when the C5 library was unavailable on NuGet, so I "physically" included the assembly in the Provision NuGet package. The authors have later made it available so this was no longer necessary. (Hence it is now referenced as a dependency)

**Comment by Lakritzator** [comment]
Ah, thanks... that explains it. The title of the issue was somehow misleading.
